export const sampleAds = (userId, categories, images = {}) => [
  {
    title: "iPhone 13 Pro Max",
    description: "Like new, barely used. 128GB, Silver.",
    price: 850,
    category: categories["Electronics"],
    location: "Warsaw",
    photos: images.electronics?.slice(0, 2) || [],
    user_id: userId,
  },
  {
    title: "MacBook Air M1",
    description: "Perfect for work. 8GB RAM, 256GB SSD.",
    price: 1100,
    category: categories["Electronics"],
    location: "Kraków",
    photos: images.electronics?.slice(1, 3) || [],
    user_id: userId,
  },
  {
    title: "Samsung 55 4K TV",
    description: "Crystal clear display with smart features.",
    price: 650,
    category: categories["Electronics"],
    location: "Gdańsk",
    photos: images.electronics?.slice(0, 1) || [],
    user_id: userId,
  },
  {
    title: "2-room apartment for rent",
    description: "Modern apartment in city center. Fully furnished.",
    price: 1200,
    category: categories["Real Estate"],
    location: "Kraków",
    photos: images.realEstate?.slice(0, 3) || [],
    user_id: userId,
  },
  {
    title: "Studio Apartment",
    description: "Perfect for students. All utilities included.",
    price: 800,
    category: categories["Real Estate"],
    location: "Warsaw",
    photos: images.realEstate?.slice(1, 2) || [],
    user_id: userId,
  },
  {
    title: "3-bedroom House",
    description: "Spacious family home with garden.",
    price: 450000,
    category: categories["Real Estate"],
    location: "Wrocław",
    photos: images.realEstate || [],
    user_id: userId,
  },
  {
    title: "Toyota Corolla 2018",
    description: "Well-maintained, diesel, low mileage.",
    price: 15000,
    category: categories["Vehicles"],
    location: "Gdańsk",
    photos: images.vehicles?.slice(0, 2) || [],
    user_id: userId,
  },
  {
    title: "BMW 320i 2019",
    description: "Luxury sedan, leather interior, automatic.",
    price: 28000,
    category: categories["Vehicles"],
    location: "Warsaw",
    photos: images.vehicles?.slice(1, 3) || [],
    user_id: userId,
  },
  {
    title: "Honda Civic 2020",
    description: "Sporty and reliable. Great fuel economy.",
    price: 22000,
    category: categories["Vehicles"],
    location: "Kraków",
    photos: images.vehicles || [],
    user_id: userId,
  },
  {
    title: "Designer Winter Coat",
    description: "Brand new, size M. Originally 800 PLN.",
    price: 400,
    category: categories["Fashion"],
    location: "Warsaw",
    photos: images.fashion?.slice(0, 2) || [],
    user_id: userId,
  },
  {
    title: "Nike Air Max",
    description: "Size 42, lightly used, great condition.",
    price: 120,
    category: categories["Fashion"],
    location: "Gdańsk",
    photos: images.fashion?.slice(1, 2) || [],
    user_id: userId,
  },
  {
    title: "IKEA Sofa Set",
    description: "3-seater with armchair. Moving sale.",
    price: 800,
    category: categories["Home & Garden"],
    location: "Wrocław",
    photos: images.homeGarden?.slice(0, 2) || [],
    user_id: userId,
  },
  {
    title: "Garden Tools Set",
    description: "Complete set including spades and rakes.",
    price: 150,
    category: categories["Home & Garden"],
    location: "Kraków",
    photos: images.homeGarden?.slice(1, 2) || [],
    user_id: userId,
  },
  {
    title: "Road Bike",
    description: "Professional carbon frame bike.",
    price: 2500,
    category: categories["Sports"],
    location: "Warsaw",
    photos: images.sports?.slice(0, 2) || [],
    user_id: userId,
  },
  {
    title: "Gym Equipment",
    description: "Dumbbells, bench, resistance bands.",
    price: 600,
    category: categories["Sports"],
    location: "Gdańsk",
    photos: images.sports?.slice(1, 2) || [],
    user_id: userId,
  },
  {
    title: "English Tutoring",
    description: "Private lessons, all levels, flexible schedule.",
    price: 50,
    category: categories["Services"],
    location: "Kraków",
    photos: [],
    user_id: userId,
  },
  {
    title: "House Cleaning",
    description: "Professional service, reliable, competitive rates.",
    price: 80,
    category: categories["Services"],
    location: "Warsaw",
    photos: [],
    user_id: userId,
  },
  {
    title: "Programming Books",
    description: "JavaScript, Python, React books collection.",
    price: 200,
    category: categories["Books"],
    location: "Wrocław",
    photos: [],
    user_id: userId,
  },
  {
    title: "Web Developer Job",
    description: "Remote React developer position, competitive salary.",
    price: 8000,
    category: categories["Jobs"],
    location: "Remote",
    photos: [],
    user_id: userId,
  },
];
